Course_work/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('__debug__/', include(debug_toolbar.urls)),
                  path('', include('mainapp.urls')),
                  path('admin/', admin.site.urls),
                  path('', include('registration.urls')),
                  path('accounts/', include('authorization.urls')),
                  path('', include('dialogs.urls')),
                  path('', include('lab22.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dialogs/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from django.urls import path, include

from .views import *
from . import views


urlpatterns = [
    url(r'dialogs/$', login_required(views.DialogsView.as_view()), name='dialogs'),
    path(r'dialogs/create/<int:user_id>/', login_required(views.CreateDialogView.as_view()), name='create_dialog'),
    url(r'dialogs/(?P<chat_id>\d+)/$', login_required(views.MessagesView.as_view()), name='messages'),
    path('all_users/', UsersListView.as_view(), name='get_users')
]

lab22/urls.py
from django.urls import path, include
from .views import *

urlpatterns = [
    path('lab22/', execprocedure, name='proc')
]

dialogs/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _


class Dialog(models.Model):
    members = models.ManyToManyField(User, verbose_name=_("Участник"))

    def get_absolute_url(self):
        return reverse('messages', kwargs={'chat_id': self.pk})

    def __str__(self):
        return f'Диалог между {" и ".join(member.username for member in self.members.all())}'


class Message(models.Model):
    chat = models.ForeignKey(Dialog, verbose_name=_("Диалог"), on_delete=models.CASCADE)
    author = models.ForeignKey(User, default='', verbose_name=_("Пользователь"), on_delete=models.CASCADE)
    message = models.TextField(_("Сообщение"))
    pub_date = models.DateTimeField(_('Дата сообщения'), default=timezone.now)
    is_read = models.BooleanField(_('Прочитано'), default=False)

    class Meta:
        ordering = ['pub_date']

    def __str__(self):
        return self.message

dialogs/forms.py
from django.forms import ModelForm

from dialogs.models import Message


class MessageForm(ModelForm):
    class Meta:
        model = Message
        fields = ['message']
        labels = {'message': ""}

dialogs/views.py
from django.contrib.auth.models import User
from django.db.models import Count
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views import View, generic

from dialogs.forms import MessageForm
from .models import Dialog


class UsersListView(generic.ListView):
    queryset = User.objects.all()
    template_name = 'users/all_users.html'
    context_object_name = 'users'


class DialogsView(View):
    def get(self, request):
        chats = Dialog.objects.filter(members__in=[request.user.id])
        return render(request, 'users/dialogs.html', {'user_profile': request.user, 'chats': chats})


class MessagesView(View):
    def get(self, request, chat_id):
        chat = Dialog.objects.get(id=chat_id)

        return render(
            request,
            'users/messages.html',
            {
                'user_profile': request.user,
                'chat': chat,
                'form': MessageForm()
            }
        )

    def post(self, request, chat_id):
        form = MessageForm(data=request.POST)
        if form.is_valid():
            message = form.save(commit=False)
            message.chat_id = chat_id
            message.author = request.user
            message.save()
        return redirect(reverse('messages', kwargs={'chat_id': chat_id}))


class CreateDialogView(View):
    def get(self, request, user_id):
        chats = Dialog.objects.filter(members__in=[request.user.id, user_id]).annotate(
            c=Count('members')).filter(c=2)
        if chats.count() == 0:
            chat = Dialog.objects.create()
            chat.members.add(request.user)
            chat.members.add(user_id)
        else:
            chat = chats.first()
        return redirect(reverse('messages', kwargs={'chat_id': chat.id}))

templates/users/all_users.html
{% extends 'mainapp/base.html' %}

{% block title %}
{% endblock %}

{% block main %}


    <div class="d-flex flex-column">
        {% for user in users %}
            <button><a href="{% url 'create_dialog' user.id %}">Написать сообщение {{ user.username }}</a>
            </button>
        {% endfor %}
    </div>


{% endblock %}

templates/users/dialogs.html
{% extends 'mainapp/base.html' %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"/>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
{% load i18n %}
{% load custom_tag %}
{% block title %}
{% endblock %}

{% block main %}
    <div class="panel">
        {% load tz %}

        {% if chats.count == 0 %}
            <div class="panel panel-body">{% trans "Нет ни одного начатого диалога" %}</div>
        {% endif %}
        {% for chat in chats %}
            {% if chat.message_set.count != 0 %}
                {% with last_message=chat.message_set.last %}
                    {% get_companion user chat as companion %}
                    <a class="list-group-item {% if companion == last_message.author and not last_message.is_readed %}unreaded{% endif %}"
                       href="{{ chat.get_absolute_url }}">
                        <div class="reply-body">
                            <ul class="list-inline">
                                <li class="drop-left-padding">
                                    <strong class="list-group-item-heading">{{ companion.username }}</strong>
                                </li>
                                <li class="pull-right text-muted"><small>{{ last_message.pub_date|utc }}</small></li>
                            </ul>
                            {% if companion != last_message.author %}
                                <div>
                                    <div class="attached-reply-body {% if not last_message.is_readed %}unreaded{% endif %}">{{ last_message.message|truncatechars_html:"200"|safe|striptags }}</div>
                                </div>
                            {% else %}
                                <div>{{ last_message.message|truncatechars_html:"200"|safe|striptags }}</div>
                            {% endif %}
                        </div>
                    </a>
                {% endwith %}
            {% endif %}
        {% endfor %}
    </div>
{% endblock %}

templates/users/message.html
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"/>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
{% load i18n %}
{% url 'profile' message_item.author.username as the_user_url%}
{% load tz %}
<div class="list-group-item {% if not message_item.is_readed %}unreaded{% endif %}">
    <div class="reply-body">
        <ul class="list-inline">
            <li class="drop-left-padding">
                <strong style="color: blue" class="list-group-item-heading">{{ message_item.author.username }}</strong>
            </li>
            <li class="pull-right text-muted"><small>{{ message_item.pub_date|utc }}</small></li>
        </ul>
        <div><h5>   {{ message_item.message|safe }}</h5></div>
    </div>
</div>

templates/users/messages.html
{% extends 'mainapp/base.html' %}

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"/>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
{% load i18n %}
{% block title %}
{% endblock %}

{% block main %}
    {% if not chat %}
        <div class="panel panel-body">
            {% trans "Невозможно начать беседу. Не найден пользователь или вы не имеете доступа к данной беседе." %}
        </div>
    {% else %}
        {% load tz %}
        {% if chat %}
            <div id="messages" class="panel">
                <div id="innerMessages">
                    {% for message in chat.message_set.all %}
                        {% include 'users/message.html' with message_item=message %}
                    {% endfor %}
                </div>
            </div>
        {% endif %}
        <div id="message_form">
            <form id="message-form" class="panel panel-body" method="post">
                {% load bootstrap3 %}
                {% csrf_token %}
                {% bootstrap_form form %}
                <button type="submit" class="btn btn-default btn-sm"
                        onclick="return ETextEditor.validateForm('message-form')"><span
                        class="ico ico-comment"></span>{% trans "Отправить" %}</button>
            </form>
        </div>
    {% endif %}
{% endblock %}